apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: naas
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./namespaces
    repoURL: https://github.com/jduimovich/naas
    targetRevision: main
  destination:
    namespace: naas
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
